---
id: dmhy
name: dmhy
description: "dmhy is a TAIWANESE Public magnet tracker for ANIME"
language: en-US
type: public
encoding: UTF-8
links:
  - https://share.dmhy.org/

caps:
  categorymappings:
    - {id: 2, cat: TV/Anime, desc: "Anime (Anime)"}
    - {id: 31, cat: TV/Anime, desc: "English (Quarterly Complete)"}
    - {id: 3, cat: Books/Comics, desc: "Manga (Manga)"}
    - {id: 41, cat: TV, desc: "English (Hong Kong and Taiwan original)"}
    - {id: 42, cat: TV, desc: "English (Japanese original)"}
    - {id: 4, cat: Audio, desc: "Music (Music)"}
    - {id: 43, cat: Audio, desc: "EnglishMusic (Anime Music)"}
    - {id: 44, cat: Audio, desc: "EnglishMusic (Fan Music)"}
    - {id: 15, cat: Audio, desc: "EnglishMusic (Pop Music)"}
    - {id: 6, cat: TV, desc: "English (Japanese TV drama)"}
    - {id: 7, cat: TV/Anime, desc: "RAW"}
    - {id: 9, cat: PC/Games, desc: "English (games)"}
    - {id: 17, cat: PC/Games, desc: "English (computer games)"}
    - {id: 18, cat: Console, desc: "English (video games)"}
    - {id: 19, cat: Console, desc: "English (console games)"}
    - {id: 20, cat: Console, desc: "English (online games)"}
    - {id: 21, cat: Console, desc: "English (game periphery)"}
    - {id: 12, cat: Other/Misc, desc: "English (special photo)"}
    - {id: 1, cat: Other, desc: "Other (other)"}
    # Anime as Movies (Radarr uses t=movie):
    - {id: 2, cat: Movies/Other, desc: "Anime (Anime)"}
    - {id: 31, cat: Movies/Other, desc: "English (Quarterly Complete)"}
    - {id: 7, cat: Movies/Other, desc: "RAW"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: flaresolverr
    type: info
    label: FlareSolverr
    default: This site may use Cloudflare DDoS Protection, therefore Prowlarr requires FlareSolverr to access it.

search:
  paths:
    - path: topics/list
  inputs:
    # https://share.dmhy.org/topics/list?keyword=one+piece&sort_id=0&team_id=0&order=date-desc
    keyword: "{{ .Keywords }}"
    sort_id: 0
    order: date-desc
    team_id: 0

  rows:
    selector: table tbody tr:has(a[href^="magnet:?"])

  fields:
    category:
      selector: td:nth-child(2) a
      attribute: href
      filters:
        - name: regexp
          args: "\\/(\\d+)$"
    title:
      selector: a[href^="/topics/view/"]
    details:
      selector: a[href^="/topics/view/"]
      attribute: href
    download:
      selector: a[href^="magnet:?"]
      attribute: href
    date:
      selector: td:nth-child(1) span
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy/MM/dd HH:mm zzz"
    size:
      selector: td:nth-child(5)
    seeders:
      selector: td:nth-child(6)
    leechers:
      selector: td:nth-child(7)
    grabs:
      selector: td:nth-child(8)
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# tedmind 1.8.1
