---
id: miobt
name: MioBT
description: "MioBT is a CHINESE Public torrent index"
language: en-US
type: public
encoding: UTF-8
links:
  - https://miobt.com/
  - https://kisssub.org/

caps:
  categorymappings:
    - {id: Anime, cat: TV/Anime, desc: Anime (Animation Series and Movies)}
    - {id: Manga, cat: Books/Comics, desc: Manga (Comics and Manga)}
    - {id: Music, cat: Audio, desc: Music (Music OST and Singles)}
    - {id: English, cat: TV/Other, desc: English (Live Action)}
    - {id: English, cat: TV/Anime, desc: English (Other)}
    - {id: Raw, cat: TV/Anime, desc: Raw}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings: []

search:
  paths:
    # https://miobt.com/search.php?keyword=moon+720p
    - path: "{{ if .Keywords }}search.php?keyword={{ .Keywords }}{{ else }}{{ end }}"

  rows:
    selector: table[id="listTable"] > tbody > tr:has( a[href^="show-"])

  fields:
    category:
      selector: a[href^="sort-"]
    title:
      selector: a[href^="show-"]
    details:
      selector: a[href^="show-"]
      attribute: href
    infohash:
      selector: a[href^="show-"]
      attribute: href
      filters:
        - name: regexp
          args: show-([0-9A-Fa-f]{40})
    date_today:
       # Today 00:35	 (Today)
      optional: true
      selector: td:nth-child(1):contains("Today")
      filters:
        - name: replace
          args: ["Today", "Today"]
        - name: append
          args: " +08:00" # CST
        - name: fuzzytime
    date_yday:
      # Yesterday 22:50	 (Yesterday)
      optional: true
      selector: td:nth-child(1):contains("Yesterday")
      filters:
        - name: replace
          args: ["Yesterday", "Yesterday"]
        - name: append
          args: " +08:00" # CST
        - name: fuzzytime
    date_year:
      # 2020/12/24
      optional: true
      selector: td:nth-child(1):not(:contains("Yesterday")):not(:contains("Today"))
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy/MM/dd zzz"
    date:
      text: "{{ if or .Result.date_year .Result.date_today .Result.date_yday }}{{ or .Result.date_year .Result.date_today .Result.date_yday }}{{ else }}now{{ end }}"
    size:
      selector: td:nth-child(4)
    seeders:
      selector: td:nth-child(5)
    leechers:
      selector: td:nth-child(6)
    grabs:
      selector: td:nth-child(7)
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine MioBT
