---
id: pttime
name: PTTime
description: "PTTime is a ratioless CHINESE Private Torrent Tracker for HD MOVIES / TV / GENERAL"
language: en-US
type: private
encoding: UTF-8
requestDelay: 2
links:
  - https://www.pttime.org/

caps:
  categorymappings:
    - {id: 401, cat: Movies, desc: "Movies(Movies)", default: true}
    - {id: 402, cat: TV, desc: "TV Series(TV Series)", default: true}
    - {id: 403, cat: TV, desc: "TV Shows(TV Shows)", default: true}
    - {id: 404, cat: TV/Documentary, desc: "Documentaries(Documentary)", default: true}
    - {id: 405, cat: TV/Sport, desc: "Sport(Sports、English、English)", default: true}
    - {id: 406, cat: PC/Games, desc: "Games(GamesEnglish)", default: true}
    - {id: 408, cat: Audio, desc: "Music(Music、English、MV、English)", default: true}
    - {id: 409, cat: Other, desc: "Art(English、English、English、English、English)", default: true}
    - {id: 411, cat: Other, desc: "Science(English、English、English)", default: true}
    - {id: 412, cat: Other, desc: "School(English、English、English)", default: true}
    - {id: 413, cat: Books, desc: "Book(English、Audiobooks)", default: true}
    - {id: 420, cat: PC, desc: "Code(IT、English、English、English", default: true}
    - {id: 430, cat: TV/Anime, desc: "Animate(3DAnime、2.5English)", default: true}
    - {id: 431, cat: TV/Anime, desc: "ACGN", default: true}
    - {id: 432, cat: TV/Other, desc: "Baby(English、English、English)", default: true}
    - {id: 450, cat: Other, desc: "Resource(English、English、English)", default: true}
    - {id: 451, cat: PC, desc: "Software(Software、English、 English、APPEnglish)", default: true}
    - {id: 490, cat: Other, desc: "Other", default: true}
    - {id: 440, cat: XXX, desc: "9kg-AV(English)", default: false}
    - {id: 441, cat: XXX, desc: "9kg-Sex(English)", default: false}
    - {id: 442, cat: XXX, desc: "9kg-III(English、EnglishMovies)", default: false}
    - {id: 443, cat: XXX, desc: "9kg-HAnime", default: false}
    - {id: 444, cat: XXX, desc: "9kg-HGames", default: false}
    - {id: 445, cat: XXX, desc: "9kg-HEnglish(English、Audiobooks)", default: false}
    - {id: 446, cat: XXX, desc: "9kg-HPhoto Set(English、English、English）", default: false}
    - {id: 447, cat: XXX, desc: "9kg-HAudio(ASMR、Music、Audio)", default: false}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, doubanid]
    movie-search: [q, imdbid, doubanid]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 4
    options:
      4: created
      7: seeders
      5: size
      1: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>100</b> on your account profile.

login:
  path: takelogin.php
  method: post
  inputs:
    loginmethod: username
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    dutime: month
    ssl: yes
  error:
    - selector: td.embedded:has(h2:contains("Failed"))
  test:
    path: index.php
    selector: a[href="logout.php"]

search:
  paths:
    - path: torrents.php
      categories: [401, 402, 403, 404, 405, 406, 408, 409, 411, 412, 413, 420, 430, 431, 432, 450, 451, 490]
    - path: adults.php
      categories: [440, 441, 442, 443, 444, 445, 446, 447]
  inputs:
    $raw: "{{ range .Categories }}cat{{.}}=1&{{end}}"
    # currently supports only one query id at one time.
    search: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ end }}{{ if or .Query.IMDBID .Query.DoubanID }} {{ else }}{{ .Keywords }}{{ end }}{{ if .Query.DoubanID }}{{ .Query.DoubanID }}{{ else }}{{ end }}"
    # 0 incldead, 1 active, 2 dead
    incldead: 0
    # 0 all, 1 normal, 2 free, 3 2x, 4 2xfree, 5 50%, 6 2x50%, 7 30%
    spstate: "{{ if .Config.freeleech }}2{{ else }}0{{ end }}"
    # 0 title, 1 descr, 2 smalldesc, 3 uploader, 4 imdburl, 5 doubanurl
    search_area: "{{ if .Query.IMDBID }}4{{ else }}{{ end }}{{ if .Query.DoubanID }}5{{ else }}{{ end }}{{ if or .Query.IMDBID .Query.DoubanID }}{{ else }}0{{ end }}"
    # 0 AND, 1 OR, 2 exact
    search_mode: 0
    sort: "{{ .Config.sort }}"
    type: "{{ .Config.type }}"
    notnewword: 1

  rows:
    selector: table.torrents > tbody > tr:has(a[href^="download.php?id="])

  fields:
    category:
      selector: a[href^="?cat="]
      attribute: href
      filters:
        - name: querystring
          args: cat
    title_default:
      selector: a[href^="details.php?id="]
    title:
      selector: a[title][href^="details.php?id="]
      attribute: title
      optional: true
      default: "{{ .Result.title_default }}"
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?id="]
      attribute: href
    poster:
      selector: td.torrentimg > img
      attribute: src
    imdbid:
      selector: a[href*="imdb.com/title/tt"]
      attribute: href
    doubanid:
      selector: a[href*="movie.douban.com/subject/"]
      attribute: href
    date_elapsed:
      # time type: time elapsed (default)
      selector: td:nth-child(5) > span[title]
      attribute: title
      optional: true
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-dd HH:mm:ss zzz"
    date_added:
      # time added
      selector: td:nth-child(5):not(:has(span))
      optional: true
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-ddHH:mm:ss zzz"
    date:
      text: "{{ if or .Result.date_elapsed .Result.date_added }}{{ or .Result.date_elapsed .Result.date_added }}{{ else }}now{{ end }}"
    size:
      selector: td:nth-child(6)
    seeders:
      selector: td:nth-child(7)
    leechers:
      selector: td:nth-child(8)
    grabs:
      selector: td:nth-child(9)
    downloadvolumefactor:
      case:
        font.promotion.free: 0
        font.promotion.twoupfree: 0
        font.promotion.halfdown: 0.5
        font.promotion.twouphalfdown: 0.5
        font.promotion.thirtypercent: 0.3
        "*": 1
    uploadvolumefactor:
      case:
        font.promotion.twoup: 2
        font.promotion.twoupfree: 2
        font.promotion.twouphalfdown: 2
        "*": 1
    description:
      selector: td:nth-child(2) > font:last-child
# NexusPHP Standard v1.5 Beta 4
