---
id: totheglory
name: ToTheGlory
description: "ToTheGlory (TTG) A Chinese tracker"
language: en-US
type: private
encoding: UTF-8
requestDelay: 2
links:
  - https://totheglory.im/

caps:
  categories:
    # Movies Movie
    MoviesDVDRip: Movies/SD # Movie DVDRip
    Movies720p: Movies/HD # Movie 720p
    Movies1080i/p: Movies/HD # Movie 1080i / p
    BluRayEnglish: Movies/BluRay # BluRay original disc
    English2160p: Movies/UHD # Media - 2160p
    UHDEnglish: Movies/UHD # Blu-ray UHD
    # Documentary Docs
    Documentary720p: Movies/HD # Documentary 720p
    Documentary1080i/p: Movies/HD # Documentary 1080i / p
    DocumentaryBluRayEnglish: Movies/BluRay # Documentary BluRay Original
    # TV Series TV
    WesternEnglish720p: TV/HD # TV Series - EU/US - 720p
    WesternEnglish1080i/p: TV/HD # TV Series - EU/US - 1080i/p
    HDEnglish: TV/HD # TV Series - JP
    English1080i/p: TV/HD # TV Series - CN - 1080i/p
    English720p: TV/HD # TV Series - CN - 720p
    HDEnglish: TV/HD # TV Series - KR
    # TV SeriesEnglish TV Packs
    WesternEnglish: TV/HD # TV Packs - EU/US
    English: TV/HD # TV Packs - JP
    English: TV/HD # TV Packs - CN
    MandarinEnglish: TV/HD # TV Packs - KR
    # Music Audio
    (MoviesEnglish&Game)OST: Audio # OST - (Movie & Game) Track
    EnglishMusicFLAC&APE: Audio/Lossless  # FLAC & APE
    MV&amp;English: Audio/Video # MV & Concert
    # Other Other
    HDSportsEnglish: TV/Sport # HD Sports
    HDAnime: TV/Anime # HD Animation
    EnglishTV Shows: TV/HD # TV Shows - KR
    HDTV Shows: TV/HD # TV Shows
    JapanTV Shows: TV/HD # TV Shows - JP
    MiniVideo: Other # MiniVideo
    EnglishAudio Track: Audio # Supplemental audio tracks
    iPhone/iPadEnglish: PC/Mobile-Other # IPhone / iPad video
    # EnglishGames
    PC: PC/Games # Games - PC
    MAC: PC/Mac # Games - MAC
    # English
    XBOX360: Console/XBox 360 # MicroSoft - XBOX360
    XBOX1: Console/XBox # MicroSoft - XBOX360
    XBLA: Console/XBox # MicroSoft - XBLA
    XBOX+to+XBOX360: Console/XBox # MicroSoft - XBOX to XBOX360
    # English
    PS2: Console/Other # SONY - PS2
    PSP: Console/PSP # SONY - PSP
    PS4: Console/PS4 # SONY - PS4
    PS3: Console/PS3 # SONY - PS3
    PSV: Console/PS Vita # SONY - PSV
    # English
    WIIU: Console/WiiU # Nintendo - WIIU
    WII: Console/Wii # Nintendo- WII
    SWITCH: Console/Other # Nintendo - SWITCH
    NDS: Console/NDS # Nintendo - NDS
    NGC: Console/Other # Nintendo - NGC
    # English
    PS3EnglishHD: Console/PS3 # Video - HD - PS3
    PSPEnglishHD&English: Console/PSP # Video - SD&HD - PSP
    XBOX360EnglishHD: Console/XBox 360 # Video - HD - XBOX360
    Game+Video: Console/Other # Video - Game Video
    # Software
    APPZ: PC # Software - APPZ
    Game+Ebook: Books/EBook # Software - Game Ebook
    Ebook: Books/EBook # Software - Ebook
    # English
    iPhone/iPadGames: PC/Mobile-iOS # Apple - Game - iPhone/iPad
    iPadEnglish: Books/EBook # Apple - Book - iPad
    iPhone/iPadSoftware: PC/Mobile-iOS # Apple - Software - iPhone/iPad

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: 2facode
    type: text
    label: 2FA code
  - name: info_2fa
    type: info
    label: "About 2FA code"
    default: "Only fill in the <b>2FA code</b> box if you have enabled <b>2FA</b> on the TTG Web Site. Otherwise just leave it empty."
  - name: passid
    type: select
    label: Security Question ID
    default: 0
    options:
      0: Security question (Ignore not set)
      1: When did your start using PT?
      2: How did you get to know about TTG?
      3: What's the name of the first movie you watched in a cinema?
      4: What's your favorite movie?
      5: Who's your favorite porn star?
      6: Who's your favorite actor/actress?
      7: What's your most anticipated movie?
  - name: info_passid
    type: info
    label: "About Security ID"
    default: "Only select the <b>Security Question ID</b> from the pulldown if you have set it on the TTG Web Site. Otherwise just leave it as ignore not set."
  - name: passan
    type: text
    label: Security Question Answer
  - name: info_passan
    type: info
    label: "About Security Question Answer"
    default: "Only fill in the <b>Security Question Answer</b> box if you have set it on the TTG Web Site. Dont forget to write your answer in the same language you saved it on the TTG Web Site. Otherwise just leave it empty."

login:
  path: login.php?returnto=
  method: form
  form: form[action="takelogin.php"]
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    rememberme: yes
    otp: "{{ .Config.2facode }}"
    passid: "{{ .Config.passid }}"
    passan: "{{ .Config.passan }}"
  error:
    - selector: td.embedded:has(h2:contains("！")) # Chinese, Japanese
    - selector: td.embedded:has(h2:contains("!")) # English, Korean
  test:
    path: my.php
    selector: a[href*="logout.php"]

search:
  paths:
    - path: browse.php
      inputs:
        c: M
    - path: browse.php
      categories: [1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 4000, 4010, 4020, 4030, 4040, 4050, 4060, 4070, 7000, 7010, 7020, 7030, 7040, 7050, 7060]
      inputs:
        c: G
  inputs:
    search_field: "{{ range .Categories }}English:`{{.}}` {{end}}{{ if .Query.IMDBID }}imdb{{ .Query.IMDBIDShort }}{{ else }}{{ .Keywords }}{{ end }}"
  rows:
    selector: table#torrent_table > tbody > tr[id]

  fields:
    description:
      selector: div.name_left > a > b
    title:
      selector: div.name_left > a > b
      remove: span
    category:
      selector: tr[id] td:nth-child(1) > a
      attribute: href
      filters:
        - name: querystring
          args: search_field
        - name: replace
          args: ["category:", ""]
        - name: trim
          args: "\""
    details:
      selector: div.name_left > a
      attribute: href
    download:
      selector: a.dl_a
      attribute: href
    files:
      selector: td:nth-child(3)
    size:
      selector: td:nth-child(7)
    seeders:
      selector: td:nth-child(9)
      filters:
        - name: split
          args: ["/", 0]
    leechers:
      selector: td:nth-child(9)
      filters:
        - name: split
          args: ["/", 1]
        - name: replace
          args: ["\n", ""]
    grabs:
      selector: td:nth-child(8)
    date:
      selector: td:nth-child(5)
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-ddHH:mm:ss zzz"
    imdbid:
      selector: span.imdb_rate > a
      attribute: href
    downloadvolumefactor:
      case:
        img[alt="free"]: 0
        img[alt="50%"]: 0.5
        img[alt="30%"]: 0.3
        "*": 1
    uploadvolumefactor:
      case:
        img[alt="200%"]: 2
        "*": 1
    minimumratio:
      case:
        img[title="Hit and Run"]: 1
        "*": 0
    minimumseedtime:
      case:
        img[title="Hit and Run"]: 216000
        "*": 0
# engine n/a
